from decouple import config

CLIENT_ID = config('CLIENT_ID')
CLIENT_SECRET = config('CLIENT_SECRET')

AUTH_URI_PORT = int(config('AUTH_URI_PORT'))
EVENTSUB_URI_PORT = int(config('EVENTSUB_URI_PORT'))
EVENTSUB_URI_ENDPOINT = config('EVENTSUB_URI_ENDPOINT')
CALLBACK_ROUTE = config('CALLBACK_ROUTE')

APP2APP_CLIENT_CREDENTIALS_GRANT_FLOW = config('APP2APP_CLIENT_CREDENTIALS_GRANT_FLOW')
CHAT_OAUTH_SCOPE = config('CHAT_OAUTH_SCOPE')
CHAT_OAUTH_ACCESS_TOKEN = config('CHAT_OAUTH_ACCESS_TOKEN')

USER_IMPLICIT_GRANT_FLOW_CODE = config('USER_IMPLICIT_GRANT_FLOW_CODE')
USER_IMPLICIT_GRANT_FLOW_ACCESS_TOKEN = config('USER_IMPLICIT_GRANT_FLOW_ACCESS_TOKEN')
USER_IMPLICIT_GRANT_FLOW_REFRESH_TOKEN = config('USER_IMPLICIT_GRANT_FLOW_REFRESH_TOKEN')

INITIAL_CHANNELS = config('INITIAL_CHANNELS').split(',')

CMD_ALLOW_LIST = ['aux', 'cat', 'cd', 'echo', 'grep', 'id', 'ipconfig', 'ls', 'man', 'netstat', 'nslookup', 'pwd',
                  'top', 'who', 'whoami']
